# Checkpoint Three: Cleaning Data

Now you are ready to clean your data. Before starting coding, provide the link to your dataset below.

My dataset: https://www.kaggle.com/datasets/antonkozyriev/game-recommendations-on-steam

Import the necessary libraries and create your dataframe(s).

In [1]:
import pandas as pd

df = pd.read_csv('games.csv', on_bad_lines='skip')
df.head()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,price_discounted,discount,steam_deck
0,11190,Sherlock Holmes versus Jack the Ripper,2009-12-23,True,False,False,Mostly Positive,78,792,9.99,9.99,9.99,0.0,True
1,20700,Starscape,2008-11-03,True,False,False,Very Positive,81,80,7.99,7.99,7.99,0.0,True
2,94202,"Jamestown: Gunpowder, Treason, & Plot",2011-11-10,True,True,False,Positive,90,10,2.99,2.99,2.99,0.0,True
3,212673,Tom Clancy's Ghost Recon Future Soldier® - Khy...,2013-02-26,True,False,False,Mixed,60,10,9.99,9.99,9.99,0.0,True
4,222520,Champions of Regnum,2013-02-27,True,True,True,Mixed,67,1098,0.00,0.00,0.00,0.0,True

In [2]:
df.shape

(13469, 14)

## Missing Data

Test your dataset for missing data and handle it as needed. Make notes in the form of code comments as to your thought process.

In [3]:
import pandas as pd
df = pd.read_csv('games.csv', on_bad_lines='skip')

df.isnull()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,price_discounted,discount,steam_deck
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13464,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13465,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13466,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13467,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13468,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
df.isnull().sum()

#It looks like the only columns with nulls are columns I need, so missing data is not something that will make us drop any columns.

app_id               0
title                0
date_release         0
win                  0
mac                  0
linux                0
rating               0
positive_ratio       0
user_reviews         0
price_final          0
price_original      26
price_discounted    26
discount             0
steam_deck           0
dtype: int64

In [5]:
df['price_original']=df['price_original'].fillna(value='no original price')
df['price_discounted']=df['price_discounted'].fillna(value='no price discounted')
df.isnull().sum()

#all nulls have been taken care of.

app_id              0
title               0
date_release        0
win                 0
mac                 0
linux               0
rating              0
positive_ratio      0
user_reviews        0
price_final         0
price_original      0
price_discounted    0
discount            0
steam_deck          0
dtype: int64

## Irregular Data

Detect outliers in your dataset and handle them as needed. Use code comments to make notes about your thought process.

In [6]:
df.describe()

#I don't see any outliers that would need to be removed.

             app_id  positive_ratio  user_reviews   price_final      discount
count  1.346900e+04    13469.000000  1.346900e+04  13469.000000  13469.000000
mean   9.756635e+05       83.520974  2.979550e+03      8.486990      8.293043
std    5.608340e+05       12.831449  7.037265e+04      9.346087     22.459214
min    4.400000e+02       24.000000  1.000000e+01      0.000000      0.000000
25%    4.894600e+05       77.000000  2.000000e+01      2.490000      0.000000
50%    9.104500e+05       86.000000  4.700000e+01      5.990000      0.000000
75%    1.419290e+06       93.000000  1.460000e+02      9.990000      0.000000
max    2.266310e+06      100.000000  6.870243e+06    149.990000     90.000000

## Unnecessary Data

Look for the different types of unnecessary data in your dataset and address it as needed. Make sure to use code comments to illustrate your thought process.

In [7]:
df=df.drop(['date_release','win','mac','linux','steam_deck'],axis=1)
df.info()

#dropped all columns that have nothing to do with my business issue.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13469 entries, 0 to 13468
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   app_id            13469 non-null  int64
 1   title             13469 non-null  object
 2   rating            13469 non-null  object
 3   positive_ratio    13469 non-null  int64
 4   user_reviews      13469 non-null  int64
 5   price_final       13469 non-null  float64
 6   price_original    13469 non-null  object
 7   price_discounted  13469 non-null  object
 8   discount          13469 non-null  float64
dtypes: float64(2), int64(3), object(4)
memory usage: 947.2+ KB

## Inconsistent Data

Check for inconsistent data and address any that arises. As always, use code comments to illustrate your thought process.

In [8]:
df.head(25)

#I do not see any inconsistencies.

,app_id,title,rating,positive_ratio,user_reviews,price_final,price_original,price_discounted,discount
0,11190,Sherlock Holmes versus Jack the Ripper,Mostly Positive,78,792,9.99,9.99,9.99,0.0
1,20700,Starscape,Very Positive,81,80,7.99,7.99,7.99,0.0
2,94202,"Jamestown: Gunpowder, Treason, & Plot",Positive,90,10,2.99,2.99,2.99,0.0
3,212673,Tom Clancy's Ghost Recon Future Soldier® - Khy...,Mixed,60,10,9.99,9.99,9.99,0.0
4,222520,Champions of Regnum,Mixed,67,1098,0.00,0.0,0.0,0.0
5,222634,Train Simulator: Union Pacific GP50 Loco Add-On,Positive,100,10,19.99,19.99,19.99,0.0
6,269150,Luxuria Superbia,Very Positive,85,68,6.99,6.99,6.99,0.0
7,279990,Bridge Constructor Playground,Mostly Positive,74,95,1.99,9.99,1.99,80.0
8,289460,RC Cars,Mostly Positive,78,300,2.99,2.99,2.99,0.0
9,333880,Braveland Wizard,Very Positive,80,342,9.99,9.99,9.99,0.0
10,354680,Adventures of Bertram Fiddle 1: A Dreadly Busi...,Very Positive,87,378,4.99,4.99,4.99,0.0
11,364329,FSX: Steam Edition - WACO YMF5 Add-On,Positive,87,16,19.99,19.99,19.99,0.0
12,385870,Monstrum - Original Soundtrack,Positive,92,14,4.99,4.99,4.99,0.0
13,396350,Bleed 2,Very Positive,96,454,9.99,9.99,9.99,0.0
14,407980,Sakura Beach 2,Mostly Positive,79,248,9.99,9.99,9.99,0.0
15,412050,HordeZ,Very Positive,83,377,16.99,16.99,16.99,0.0
16,415680,Europa Universalis IV: Sabaton Soundtrack,Very Positive,94,232,2.99,2.99,2.99,0.0
17,436070,Nadia Was Here,Positive,90,31,11.99,11.99,11.99,0.0
18,436160,The Panic Room. House of secrets,Mixed,55,420,0.00,0.0,0.0,0.0
19,449360,Momodora: Reverie Under the Moonlight OST,Very Positive,98,55,1.19,2.99,1.19,60.0
20,451010,Kittypocalypse,Very Positive,88,188,14.99,14.99,14.99,0.0
21,487020,Fantasy Mosaics 14: Fourth Color,Positive,92,25,6.99,6.99,6.99,0.0
22,490860,DashBored,Positive,82,41,4.99,4.99,4.99,0.0
23,525910,Cockroach VR,Positive,94,35,1.99,1.99,1.99,0.0
24,570770,古剑奇谭二(GuJian2),Mostly Positive,77,2266,11.19,15.99,11.19,30.0

## Summarize Your Results

Make note of your answers to the following questions.

1. Did you find all four types of dirty data in your dataset? No, only some applied to my dataset.
2. Did the process of cleaning your data give you new insights into your dataset? Nothing I already knew from the EDA step
3. Is there anything you would like to make note of when it comes to manipulating the data and making visualizations? No.

In [13]:
df.to_csv('games.csv')